---
language: node_js
node_js:
  - "8.1.0"

sudo: false

cache:
  yarn: true

env:
  - PACKAGE_NAME=lerna-example-redux-lib
  - PACKAGE_NAME=lerna-example-mobile
  - PACKAGE_NAME=lerna-example-macos
  - PACKAGE_NAME=lerna-example-web

before_install:
  - npm install --global yarn@0.27.5
  - yarn setup
  - cd ./packages/$PACKAGE_NAME

install:
  - yarn install --pure-lockfile

script:
  - yarn test
